name: CI Pipeline

on:
    push:
        branches:
            - main # Sadece 'main' branch'e yapılan push'larda çalışır

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Kaynak kodu çek
            - name: Checkout code
              uses: actions/checkout@v3

            # Node.js ortamı kur
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16"

            # Bağımlılıkları yükle
            - name: Install dependencies
              run: npm install

            # Projeyi build et
            - name: Build the project
              run: npm run build

            # Build sonuçlarını doğrula
            - name: Verify build output
              run: |
                  if [ ! -d "dist" ]; then
                    echo "Build failed. 'dist' directory not found."
                    exit 1
                  fi
