name: Angular Build and Deploy to S3 with Backup

on:
    push:
        branches:
            - main # veya master dalı için "master"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install Dependencies
              run: npm install

            - name: Build Angular Application
              run: npm run build -- --configuration production

            # Eski sürümü yedekle
            - name: Backup Previous Build
              run: |
                  TIMESTAMP=$(date +%Y%m%d%H%M%S)
                  aws s3 cp s3://devops-old-version-app-bucket/ s3://devops-old-version-app-bucket/backups/$TIMESTAMP/ --recursive

            # Yeni sürümü S3'ye yükle
            - name: Deploy to S3
              run: aws s3 sync dist/sakai-ng s3://devops-old-version-app-bucket --delete
