name: Angular Build and Deploy to S3

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            # 1. Kodun Depodan Çekilmesi
            - name: Check out repository
              uses: actions/checkout@v3

            # 2. Node.js Ortamının Kurulması
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            # 3. Bağımlılıkların Kurulması
            - name: Install Dependencies
              run: npm install

            # 4. Angular Uygulamasının Derlenmesi
            - name: Build Angular Application
              run: npm run build -- --configuration production

            # 5. AWS CLI'nin Kurulması
            - name: Configure AWS CLI
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1 # Bölgenizi buraya yazın

            # 6. S3'ye Yükleme
            - name: Deploy to S3
              run: |
                  aws s3 sync dist/your-project-name s3://devops-old-version-app-bucket --delete
