name: CI/CD for Angular App with Kops

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Checkout repo
            - name: Checkout repository
              uses: actions/checkout@v3

            # Set up Node.js environment
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16"

            # Install dependencies
            - name: Install dependencies
              run: npm install

            # Build Angular app
            - name: Build Angular app
              run: npm run build -- --configuration=production --project=sakai-ng

            # Set up Docker
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            # Log in to Docker Hub
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # Build Docker image
            - name: Build Docker Image
              run: |
                  docker build -t angular-app:latest .

            # Tag and push Docker image to Docker Hub
            - name: Tag and Push Docker image
              run: |
                  docker tag angular-app:latest ${{ secrets.DOCKER_USERNAME }}/angular-app:latest
                  docker push ${{ secrets.DOCKER_USERNAME }}/angular-app:latest

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            # Checkout repo
            - name: Checkout repository
              uses: actions/checkout@v3

            # Configure AWS credentials
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            # Set up kubectl
            - name: Setup kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: "v1.23.6"

            # Set up Kops
            - name: Setup Kops
              run: |
                  curl -Lo kops https://github.com/kubernetes/kops/releases/download/v1.23.0/kops-linux-amd64
                  chmod +x ./kops
                  sudo mv ./kops /usr/local/bin/

            # Update Kubernetes cluster with new Docker image
            - name: Deploy to Kubernetes
              env:
                  KOPS_STATE_STORE: ${{ secrets.KOPS_STATE_STORE }}
              run: |
                  kops export kubecfg --name myk8scluster.k8s.local
                  kubectl set image deployment/angular-app-deployment angular-app=${{ secrets.DOCKER_USERNAME }}/angular-app:latest
