name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Install SSH Key
              run: |
                  echo "${{ secrets.EC2_KEY }}" > private_key.pem
                  chmod 600 private_key.pem

            - name: Deploy to EC2
              uses: appleboy/ssh-action@v0.1.5
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ec2-user
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                      cd /home/ec2-user/<your-angular-project>
                      git pull origin main
                      npm install
                      ng build --prod
                      sudo systemctl restart nginx
