name: Push Notification to Slack

on: 
  push:
    branches:
      - main  # veya izlemek istediğiniz başka bir branch
jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Yeni bir push yapıldı!"}' $SLACK_WEBHOOK_URL
